### ISSUE TITLE
Make generator splitting/forking easier

### ISSUE THREAD

**Issue by jimbol** [jimbol/generator-test-runner#3]
I want to easily and cleanly be able to split generator definitions so that forked logic in generators is easier to test.

```es6
let partialRunner;
beforeEach(() => {
  partialRunner = genRunner(generator).
    .next('a')
    .next('b');
  // no done yet
});

context('condition', () => {
  let run;
  beforeEach(() => {
    const completedRunner = partialRunner
      .next('c')
      .next('d')
      .next('done');

    run = completedRunner.run();
  });
});

```

**Comment by neurosnap** [comment]
Here is a gist I wrote awhile back to possibly make forking easier?  IDK it might be helpful.

https://gist.github.com/neurosnap/c86c6ae8a23aa122413ce7fb6f1a9864

**Comment by jimbol** [comment]
The current set up, combined with `beforeEach` statements, actually handles forking well: https://github.com/jimbol/generator-test-runner#forking
